### ISSUE TITLE
Placement of widgets

### ISSUE THREAD

**Issue by dbc2201** [coderkabh/Stone-Paper-Scissors#1]
Nice effort!  
Having said that, the UI is a bit confusing for a first-timer, it takes some prodding to figure out what does what. For the simple mechanics of this game, the UI could be much simpler.

**Comment by coderkabh** [comment]
Sure!
I'll work on it and will be updating it ASAP.
Thanks for your feedback.

**Comment by coderkabh** [comment]
Hi @dbc2201 ! 
I have added a border and made it a little bit more easy to understand the game.
Thanks.
